Rails:
  Enabled: true
AllCops:
  Exclude:
    - bin/*
Style/StringLiterals:
  EnforcedStyle: double_quotes
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 140
Style/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/AndOr:
  EnforcedStyle: conditionals
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/FrozenStringLiteralComment:
  Enabled: false
